---
- name: Configure openSSL Config file - Section CA_default
  ansible.builtin.lineinfile:
    path: "/etc/ssl/openssl.cnf"
    regexp: "^#?{{ item.key }} *= "
    # insertafter: "^# *{{ item.key }} = "
    insertafter: "^[ CA_default ]"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  become: yes
  with_dict: 
    "dir":           "{{ default_path.data_path }}/ssl-ca/{{ ssl_certificate_authority.ssl_certificate.organizationName }}"
    "certs":         "$dir/server/certs"
    "crl_dir":       "$dir/server/crl"
    "database":      "$dir/server/index.db"
    "new_certs_dir": "$dir/server/newcerts"
    "certificate":   "$dir/intermediate-ca/certs/{{ ssl_certificate_authority.master_intermediate_cert }}.{{ ssl_certificate_authority.ssl_certificate.organizationName}}.pem"
    "serial":        "$dir/server/serial"
    "crlnumber":     "$dir/server/crlnumber"
    "crl":           "$dir/server/crl/crl.pem"
    "private_key":   "$dir/intermediate-ca/private/{{ ssl_certificate_authority.master_intermediate_cert }}.{{ ssl_certificate_authority.ssl_certificate.organizationName}}.pem"