---
- name: Install openssl-Package
  apt:
    name: [ "openssl", "python3-openssl", "python3-cryptography" ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes

- name: "Generate local directories"
  file:
    path: "{{ item.directory }}"
    owner: "root"
    group: "root"
    state: directory
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { "directory": "/etc/ssl/csr", "mode": "0755" }
    - { "directory": "/etc/ssl/private", "mode": "0700" }
