---
- name: Install openssl
  include_tasks: install/install-openssl.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"
    - (services is defined) and ('ssl_certificate_authority' in services)
    # - services is defined
    # - 'ssl_certificate_authority' in services

- name: Install openssl on local hosts
  include_tasks: install/install-openssl_local.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"

- name: Configure openssl
  include_tasks: install/configure-openssl.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"
    - (services is defined) and ('ssl_certificate_authority' in services)

- name: Install letsencrypt
  include_tasks: install/install-letsencrypt.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "letsencrypt"
    - (services is defined) and ('ssl_certificate_authority' in services)

- name: Generate root-certificate with openssl
  include_tasks: common-ca/generate_master_certificate.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"
    - (services is defined) and ('ssl_certificate_authority' in services)
    - ssl_certificate_authority.create_master_certificate is true

- name: Generate intermediate-certificates with openssl
  include_tasks: common-ca/generate_intermediate_certificate.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"
    - (services is defined) and ('ssl_certificate_authority' in services)
    - ssl_certificate_authority.create_master_certificate is true

- name: Distributes root- and intermediate-certificates and install rootCA
  include_tasks: common-ca/distribute_keys.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"

- name: Generate global mapping
  include_tasks: generate_mapping_tables.yml
  # no_log: true

- name: Generate server-certificates with openssl
  include_tasks: common-ca/generate_server_certificate.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"

- name: Generate device-certificates with openssl
  include_tasks: common-ca/generate_device_certificates.yml
  when:
    - ssl_certificate_authority is defined
    - ssl_certificate_authority.type == "openssl"
    - (services is defined) and ('ssl_certificate_authority' in services)
    - ssl_certificate_authority.create_master_certificate is true

# - name: Generate CSR for Certificate Authority
#   include_tasks: generate_csr.yml

