---
- name: Install openssl mit openssl
  include_tasks: install-openssl.yml
  when:
    - openssl is defined
    - ssl_certificate is defined
    - ssl_certificate.type == "openssl"
    - ssl_certificate_authority in services

- name: Install openssl mit letsencrypt
  include_tasks: install-letsencrypt.yml
  when:
    - openssl is defined
    - ssl_certificate is defined
    - ssl_certificate.type == "letsencrypt"
    - ssl_certificate_authority in services

- name: Generate root-certificate
  include_tasks: generate_master_certificate.yml
  when:
    - openssl is defined
    - ssl_certificate is defined
    - ssl_certificate_authority in services