- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/crt/ansible.com.crt
    privatekey_path: "{{ default_path.data_path }}/ssl/private/{{ network.domain }}.pem"
    csr_path: "{{ default_path.data_path }}/ssl/csr/{{ network.domain }}.csr"
    provider: selfsigned
  delegate_to: "{{ ssl_ca_master }}"
  run_once: yes
  become: yes

- name: Set chmod on private key
  file:
    path: "{{ default_path.data_path }}/ssl/private"
    mode: "0400"
    owner: "{{ default_user.ssl.user }}"
    group: "{{ default_user.ssl.group }}"


---


- name: Generate Self-Signed Certificate
  command: "openssl req -newkey {{ ssl_certificate_self_signed_options }} -keyout {{ ssl_certificate_path_private }} -out {{ ssl_certificate_path_public }} -extensions v3_ca"
  args:
    creates: "{{ ssl_certificate_path_public }}"
  when: ssl_certificate_self_signed | bool
  notify: Upload Combined Public/Private Key (Self-Signed)
  tags:
    - ssl-certificate

- name: Set chmod on private key
  file:
    path: "{{ ssl_certificate_path_private }}"
    mode: "0400"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
  when: ssl_certificate_self_signed | bool
  notify: Upload Combined Public/Private Key (Self-Signed)
  tags:
    - ssl-certificate

- name: Upload Public Certificate
  template:
    src: template.certificate
    dest: "{{ ssl_certificate_path_public }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0440
  when: not ssl_certificate_self_signed | bool
  tags:
    - ssl-certificate

- name: Upload Private Key
  template:
    src: template.key
    dest: "{{ ssl_certificate_path_private }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0400
  when: not ssl_certificate_self_signed | bool
  tags:
    - ssl-certificate

- name: Upload Combined Public/Private Key
  template:
    src: template.combined
    dest: "{{ ssl_certificate_path_combined }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0400
  when: ssl_certificate_combined or ssl_certificate_self_signed | bool
  tags:
    - ssl-certificate